# Generated by Django 5.2.7 on 2025-12-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='littlelemon.category'),
        ),
    ]
