# Generated by Django 5.2.7 on 2025-12-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0002_delete_items_alter_menuitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='littlelemon.category'),
        ),
    ]
